name: Build this repo on-prem.

on:
  push:
    branches:
      - main
      - master
      - release**
  workflow_dispatch:
  schedule:
    - cron: "35 1 * * *"

jobs:
  call-reusable-workflow:
    if: github.repository == 'EG-A-S/Public-IntegrationExamples'
    uses: EG-A-S/GitHub-Actions-Tools/.github/workflows/tfs-trigger-build.yml@main
    secrets: inherit
    permissions: write-all
