name: Build this repo on-prem.

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:   # Allows you to run this workflow manually from the Actions tab

jobs:
  call-reusable-workflow:
    uses: EG-A-S/GitHub-Actions-Tools/.github/workflows/tfs-trigger-build.yml@main
    secrets:
      inherit
